### ISSUE TITLE
How can I get the dataset named `Sensitive Prompt Dataset.xlsx'?

### ISSUE THREAD

**Issue by rain305f** [researchcode001/daca#4]
Thanks for the great work！ 
But I can not find the dataset `Sensitive Prompt Dataset.xlsx'

**Comment by researchcode001** [comment]
Thank you very much for your interest in our project!
We have upgraded the original dataset  `Sensitive Prompt Dataset.xlsx' to a new one, '[VBCDE-100.txt](https://github.com/researchcode001/Divide-and-Conquer-Attack/blob/main/VBCDE-100.txt)': We have expanded the dataset from four to five categories of prompts, and enhanced the grammatical structure and expressive diversity of the prompts. 
Thank you for your interest in the DACA, and we hope this answers your question.
